/*
 * PayQuickerSDK
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.mypayquicker.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * WebhookNamespaces to be used.
 */
public enum WebhookNamespaces {
    BANKACCOUNTS_CREATED,

    BANKACCOUNTS_UPDATED_DETAILS_MODIFIED,

    BANKACCOUNTS_UPDATED_STATUS_APPROVED,

    BANKACCOUNTS_UPDATED_STATUS_COMPLIANCEHOLD,

    BANKACCOUNTS_UPDATED_STATUS_DELETED,

    PAPERCHECKS_CREATED,

    PAPERCHECKS_UPDATED_DETAILS_MODIFIED,

    PAPERCHECKS_UPDATED_STATUS_CANCELLED,

    PAPERCHECKS_UPDATED_STATUS_INPROGRESS,

    PAPERCHECKS_UPDATED_STATUS_REDEEMED,

    PAYMENTQUOTES_ACCEPTED,

    PAYMENTQUOTES_CANCELLED,

    PAYMENTQUOTES_CREATED,

    PAYMENTQUOTES_VOIDED,

    PREPAIDCARDS_CREATED,

    PREPAIDCARDS_UPDATED_STATUS_ACTIVE,

    PREPAIDCARDS_UPDATED_STATUS_CLOSED,

    PREPAIDCARDS_UPDATED_STATUS_CLOSEDEXPIRED,

    PREPAIDCARDS_UPDATED_STATUS_CLOSEDFRAUD,

    PREPAIDCARDS_UPDATED_STATUS_CLOSEDLOST,

    PREPAIDCARDS_UPDATED_STATUS_CLOSEDSTOLEN,

    PREPAIDCARDS_UPDATED_STATUS_COMPLIANCEHOLD,

    PREPAIDCARDS_UPDATED_STATUS_PENDINGACTIVATION,

    PREPAIDCARDS_UPDATED_STATUS_PENDINGORDER,

    PREPAIDCARDS_UPDATED_STATUS_PENDINGRELEASE,

    PREPAIDCARDS_UPDATED_STATUS_SUSPENDED,

    RECEIPTS_CREATED,

    RECEIPTS_UPDATED_DETAILS_MODIFIED,

    RECEIPTS_UPDATED_STATUS_CANCELLED,

    RECEIPTS_UPDATED_STATUS_COMPLETED,

    RECEIPTS_UPDATED_STATUS_EXPIRED,

    RECEIPTS_UPDATED_STATUS_FAILED,

    RECEIPTS_UPDATED_STATUS_PENDING,

    RECEIPTS_UPDATED_STATUS_PROCESSING,

    RECEIPTS_UPDATED_STATUS_REFUNDED,

    RECEIPTS_UPDATED_STATUS_RETURNED,

    RECEIPTS_UPDATED_STATUS_REVERSED,

    RECEIPTS_UPDATED_STATUS_REVIEWREQUIRED,

    RECEIPTS_UPDATED_STATUS_SCHEDULED,

    SPENDBACKQUOTES_ACCEPTED,

    SPENDBACKQUOTES_CANCELLED,

    SPENDBACKQUOTES_CREATED,

    SPENDBACKQUOTES_VOIDED,

    TRANSFERQUOTES_ACCEPTED,

    TRANSFERQUOTES_CANCELLED,

    TRANSFERQUOTES_CREATED,

    TRANSFERQUOTES_VOIDED,

    USEREVENTS_COMPLETED,

    USEREVENTS_STARTED,

    USEREVENTS_UPDATED,

    USERS_CREATED,

    USERS_UPDATED_IDV_FAILED,

    USERS_UPDATED_IDV_PASSED,

    USERS_UPDATED_KYC_APPROVED,

    USERS_UPDATED_KYC_PROVIDED,

    USERS_UPDATED_KYC_REJECTED,

    USERS_UPDATED_KYC_REQUIRED,

    USERS_UPDATED_STATUS_REGISTRATIONCOMPLETE,

    USERS_UPDATED_STATUS_REGISTRATIONINPROGRESS,

    ELECTRONICWALLETS_CREATED,

    ELECTRONICWALLETS_UPDATED_DETAILS_MODIFIED,

    ELECTRONICWALLETS_UPDATED_STATUS_APPROVED,

    ELECTRONICWALLETS_UPDATED_STATUS_COMPLIANCEHOLD,

    ELECTRONICWALLETS_UPDATED_STATUS_DELETED,

    UNKNOWN;


    private static TreeMap<String, WebhookNamespaces> valueMap = new TreeMap<>();
    private String value;

    static {
        BANKACCOUNTS_CREATED.value = "BANKACCOUNTS.CREATED";
        BANKACCOUNTS_UPDATED_DETAILS_MODIFIED.value = "BANKACCOUNTS.UPDATED.DETAILS.MODIFIED";
        BANKACCOUNTS_UPDATED_STATUS_APPROVED.value = "BANKACCOUNTS.UPDATED.STATUS.APPROVED";
        BANKACCOUNTS_UPDATED_STATUS_COMPLIANCEHOLD.value = "BANKACCOUNTS.UPDATED.STATUS.COMPLIANCEHOLD";
        BANKACCOUNTS_UPDATED_STATUS_DELETED.value = "BANKACCOUNTS.UPDATED.STATUS.DELETED";
        PAPERCHECKS_CREATED.value = "PAPERCHECKS.CREATED";
        PAPERCHECKS_UPDATED_DETAILS_MODIFIED.value = "PAPERCHECKS.UPDATED.DETAILS.MODIFIED";
        PAPERCHECKS_UPDATED_STATUS_CANCELLED.value = "PAPERCHECKS.UPDATED.STATUS.CANCELLED";
        PAPERCHECKS_UPDATED_STATUS_INPROGRESS.value = "PAPERCHECKS.UPDATED.STATUS.INPROGRESS";
        PAPERCHECKS_UPDATED_STATUS_REDEEMED.value = "PAPERCHECKS.UPDATED.STATUS.REDEEMED";
        PAYMENTQUOTES_ACCEPTED.value = "PAYMENTQUOTES.ACCEPTED";
        PAYMENTQUOTES_CANCELLED.value = "PAYMENTQUOTES.CANCELLED";
        PAYMENTQUOTES_CREATED.value = "PAYMENTQUOTES.CREATED";
        PAYMENTQUOTES_VOIDED.value = "PAYMENTQUOTES.VOIDED";
        PREPAIDCARDS_CREATED.value = "PREPAIDCARDS.CREATED";
        PREPAIDCARDS_UPDATED_STATUS_ACTIVE.value = "PREPAIDCARDS.UPDATED.STATUS.ACTIVE";
        PREPAIDCARDS_UPDATED_STATUS_CLOSED.value = "PREPAIDCARDS.UPDATED.STATUS.CLOSED";
        PREPAIDCARDS_UPDATED_STATUS_CLOSEDEXPIRED.value = "PREPAIDCARDS.UPDATED.STATUS.CLOSEDEXPIRED";
        PREPAIDCARDS_UPDATED_STATUS_CLOSEDFRAUD.value = "PREPAIDCARDS.UPDATED.STATUS.CLOSEDFRAUD";
        PREPAIDCARDS_UPDATED_STATUS_CLOSEDLOST.value = "PREPAIDCARDS.UPDATED.STATUS.CLOSEDLOST";
        PREPAIDCARDS_UPDATED_STATUS_CLOSEDSTOLEN.value = "PREPAIDCARDS.UPDATED.STATUS.CLOSEDSTOLEN";
        PREPAIDCARDS_UPDATED_STATUS_COMPLIANCEHOLD.value = "PREPAIDCARDS.UPDATED.STATUS.COMPLIANCEHOLD";
        PREPAIDCARDS_UPDATED_STATUS_PENDINGACTIVATION.value = "PREPAIDCARDS.UPDATED.STATUS.PENDINGACTIVATION";
        PREPAIDCARDS_UPDATED_STATUS_PENDINGORDER.value = "PREPAIDCARDS.UPDATED.STATUS.PENDINGORDER";
        PREPAIDCARDS_UPDATED_STATUS_PENDINGRELEASE.value = "PREPAIDCARDS.UPDATED.STATUS.PENDINGRELEASE";
        PREPAIDCARDS_UPDATED_STATUS_SUSPENDED.value = "PREPAIDCARDS.UPDATED.STATUS.SUSPENDED";
        RECEIPTS_CREATED.value = "RECEIPTS.CREATED";
        RECEIPTS_UPDATED_DETAILS_MODIFIED.value = "RECEIPTS.UPDATED.DETAILS.MODIFIED";
        RECEIPTS_UPDATED_STATUS_CANCELLED.value = "RECEIPTS.UPDATED.STATUS.CANCELLED";
        RECEIPTS_UPDATED_STATUS_COMPLETED.value = "RECEIPTS.UPDATED.STATUS.COMPLETED";
        RECEIPTS_UPDATED_STATUS_EXPIRED.value = "RECEIPTS.UPDATED.STATUS.EXPIRED";
        RECEIPTS_UPDATED_STATUS_FAILED.value = "RECEIPTS.UPDATED.STATUS.FAILED";
        RECEIPTS_UPDATED_STATUS_PENDING.value = "RECEIPTS.UPDATED.STATUS.PENDING";
        RECEIPTS_UPDATED_STATUS_PROCESSING.value = "RECEIPTS.UPDATED.STATUS.PROCESSING";
        RECEIPTS_UPDATED_STATUS_REFUNDED.value = "RECEIPTS.UPDATED.STATUS.REFUNDED";
        RECEIPTS_UPDATED_STATUS_RETURNED.value = "RECEIPTS.UPDATED.STATUS.RETURNED";
        RECEIPTS_UPDATED_STATUS_REVERSED.value = "RECEIPTS.UPDATED.STATUS.REVERSED";
        RECEIPTS_UPDATED_STATUS_REVIEWREQUIRED.value = "RECEIPTS.UPDATED.STATUS.REVIEWREQUIRED";
        RECEIPTS_UPDATED_STATUS_SCHEDULED.value = "RECEIPTS.UPDATED.STATUS.SCHEDULED";
        SPENDBACKQUOTES_ACCEPTED.value = "SPENDBACKQUOTES.ACCEPTED";
        SPENDBACKQUOTES_CANCELLED.value = "SPENDBACKQUOTES.CANCELLED";
        SPENDBACKQUOTES_CREATED.value = "SPENDBACKQUOTES.CREATED";
        SPENDBACKQUOTES_VOIDED.value = "SPENDBACKQUOTES.VOIDED";
        TRANSFERQUOTES_ACCEPTED.value = "TRANSFERQUOTES.ACCEPTED";
        TRANSFERQUOTES_CANCELLED.value = "TRANSFERQUOTES.CANCELLED";
        TRANSFERQUOTES_CREATED.value = "TRANSFERQUOTES.CREATED";
        TRANSFERQUOTES_VOIDED.value = "TRANSFERQUOTES.VOIDED";
        USEREVENTS_COMPLETED.value = "USEREVENTS.COMPLETED";
        USEREVENTS_STARTED.value = "USEREVENTS.STARTED";
        USEREVENTS_UPDATED.value = "USEREVENTS.UPDATED";
        USERS_CREATED.value = "USERS.CREATED";
        USERS_UPDATED_IDV_FAILED.value = "USERS.UPDATED.IDV.FAILED";
        USERS_UPDATED_IDV_PASSED.value = "USERS.UPDATED.IDV.PASSED";
        USERS_UPDATED_KYC_APPROVED.value = "USERS.UPDATED.KYC.APPROVED";
        USERS_UPDATED_KYC_PROVIDED.value = "USERS.UPDATED.KYC.PROVIDED";
        USERS_UPDATED_KYC_REJECTED.value = "USERS.UPDATED.KYC.REJECTED";
        USERS_UPDATED_KYC_REQUIRED.value = "USERS.UPDATED.KYC.REQUIRED";
        USERS_UPDATED_STATUS_REGISTRATIONCOMPLETE.value = "USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE";
        USERS_UPDATED_STATUS_REGISTRATIONINPROGRESS.value = "USERS.UPDATED.STATUS.REGISTRATIONINPROGRESS";
        ELECTRONICWALLETS_CREATED.value = "ELECTRONICWALLETS.CREATED";
        ELECTRONICWALLETS_UPDATED_DETAILS_MODIFIED.value = "ELECTRONICWALLETS.UPDATED.DETAILS.MODIFIED";
        ELECTRONICWALLETS_UPDATED_STATUS_APPROVED.value = "ELECTRONICWALLETS.UPDATED.STATUS.APPROVED";
        ELECTRONICWALLETS_UPDATED_STATUS_COMPLIANCEHOLD.value = "ELECTRONICWALLETS.UPDATED.STATUS.COMPLIANCEHOLD";
        ELECTRONICWALLETS_UPDATED_STATUS_DELETED.value = "ELECTRONICWALLETS.UPDATED.STATUS.DELETED";
        UNKNOWN.value = "UNKNOWN";

        valueMap.put("BANKACCOUNTS.CREATED", BANKACCOUNTS_CREATED);
        valueMap.put("BANKACCOUNTS.UPDATED.DETAILS.MODIFIED", BANKACCOUNTS_UPDATED_DETAILS_MODIFIED);
        valueMap.put("BANKACCOUNTS.UPDATED.STATUS.APPROVED", BANKACCOUNTS_UPDATED_STATUS_APPROVED);
        valueMap.put("BANKACCOUNTS.UPDATED.STATUS.COMPLIANCEHOLD", BANKACCOUNTS_UPDATED_STATUS_COMPLIANCEHOLD);
        valueMap.put("BANKACCOUNTS.UPDATED.STATUS.DELETED", BANKACCOUNTS_UPDATED_STATUS_DELETED);
        valueMap.put("PAPERCHECKS.CREATED", PAPERCHECKS_CREATED);
        valueMap.put("PAPERCHECKS.UPDATED.DETAILS.MODIFIED", PAPERCHECKS_UPDATED_DETAILS_MODIFIED);
        valueMap.put("PAPERCHECKS.UPDATED.STATUS.CANCELLED", PAPERCHECKS_UPDATED_STATUS_CANCELLED);
        valueMap.put("PAPERCHECKS.UPDATED.STATUS.INPROGRESS", PAPERCHECKS_UPDATED_STATUS_INPROGRESS);
        valueMap.put("PAPERCHECKS.UPDATED.STATUS.REDEEMED", PAPERCHECKS_UPDATED_STATUS_REDEEMED);
        valueMap.put("PAYMENTQUOTES.ACCEPTED", PAYMENTQUOTES_ACCEPTED);
        valueMap.put("PAYMENTQUOTES.CANCELLED", PAYMENTQUOTES_CANCELLED);
        valueMap.put("PAYMENTQUOTES.CREATED", PAYMENTQUOTES_CREATED);
        valueMap.put("PAYMENTQUOTES.VOIDED", PAYMENTQUOTES_VOIDED);
        valueMap.put("PREPAIDCARDS.CREATED", PREPAIDCARDS_CREATED);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.ACTIVE", PREPAIDCARDS_UPDATED_STATUS_ACTIVE);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.CLOSED", PREPAIDCARDS_UPDATED_STATUS_CLOSED);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.CLOSEDEXPIRED", PREPAIDCARDS_UPDATED_STATUS_CLOSEDEXPIRED);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.CLOSEDFRAUD", PREPAIDCARDS_UPDATED_STATUS_CLOSEDFRAUD);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.CLOSEDLOST", PREPAIDCARDS_UPDATED_STATUS_CLOSEDLOST);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.CLOSEDSTOLEN", PREPAIDCARDS_UPDATED_STATUS_CLOSEDSTOLEN);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.COMPLIANCEHOLD", PREPAIDCARDS_UPDATED_STATUS_COMPLIANCEHOLD);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.PENDINGACTIVATION", PREPAIDCARDS_UPDATED_STATUS_PENDINGACTIVATION);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.PENDINGORDER", PREPAIDCARDS_UPDATED_STATUS_PENDINGORDER);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.PENDINGRELEASE", PREPAIDCARDS_UPDATED_STATUS_PENDINGRELEASE);
        valueMap.put("PREPAIDCARDS.UPDATED.STATUS.SUSPENDED", PREPAIDCARDS_UPDATED_STATUS_SUSPENDED);
        valueMap.put("RECEIPTS.CREATED", RECEIPTS_CREATED);
        valueMap.put("RECEIPTS.UPDATED.DETAILS.MODIFIED", RECEIPTS_UPDATED_DETAILS_MODIFIED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.CANCELLED", RECEIPTS_UPDATED_STATUS_CANCELLED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.COMPLETED", RECEIPTS_UPDATED_STATUS_COMPLETED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.EXPIRED", RECEIPTS_UPDATED_STATUS_EXPIRED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.FAILED", RECEIPTS_UPDATED_STATUS_FAILED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.PENDING", RECEIPTS_UPDATED_STATUS_PENDING);
        valueMap.put("RECEIPTS.UPDATED.STATUS.PROCESSING", RECEIPTS_UPDATED_STATUS_PROCESSING);
        valueMap.put("RECEIPTS.UPDATED.STATUS.REFUNDED", RECEIPTS_UPDATED_STATUS_REFUNDED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.RETURNED", RECEIPTS_UPDATED_STATUS_RETURNED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.REVERSED", RECEIPTS_UPDATED_STATUS_REVERSED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.REVIEWREQUIRED", RECEIPTS_UPDATED_STATUS_REVIEWREQUIRED);
        valueMap.put("RECEIPTS.UPDATED.STATUS.SCHEDULED", RECEIPTS_UPDATED_STATUS_SCHEDULED);
        valueMap.put("SPENDBACKQUOTES.ACCEPTED", SPENDBACKQUOTES_ACCEPTED);
        valueMap.put("SPENDBACKQUOTES.CANCELLED", SPENDBACKQUOTES_CANCELLED);
        valueMap.put("SPENDBACKQUOTES.CREATED", SPENDBACKQUOTES_CREATED);
        valueMap.put("SPENDBACKQUOTES.VOIDED", SPENDBACKQUOTES_VOIDED);
        valueMap.put("TRANSFERQUOTES.ACCEPTED", TRANSFERQUOTES_ACCEPTED);
        valueMap.put("TRANSFERQUOTES.CANCELLED", TRANSFERQUOTES_CANCELLED);
        valueMap.put("TRANSFERQUOTES.CREATED", TRANSFERQUOTES_CREATED);
        valueMap.put("TRANSFERQUOTES.VOIDED", TRANSFERQUOTES_VOIDED);
        valueMap.put("USEREVENTS.COMPLETED", USEREVENTS_COMPLETED);
        valueMap.put("USEREVENTS.STARTED", USEREVENTS_STARTED);
        valueMap.put("USEREVENTS.UPDATED", USEREVENTS_UPDATED);
        valueMap.put("USERS.CREATED", USERS_CREATED);
        valueMap.put("USERS.UPDATED.IDV.FAILED", USERS_UPDATED_IDV_FAILED);
        valueMap.put("USERS.UPDATED.IDV.PASSED", USERS_UPDATED_IDV_PASSED);
        valueMap.put("USERS.UPDATED.KYC.APPROVED", USERS_UPDATED_KYC_APPROVED);
        valueMap.put("USERS.UPDATED.KYC.PROVIDED", USERS_UPDATED_KYC_PROVIDED);
        valueMap.put("USERS.UPDATED.KYC.REJECTED", USERS_UPDATED_KYC_REJECTED);
        valueMap.put("USERS.UPDATED.KYC.REQUIRED", USERS_UPDATED_KYC_REQUIRED);
        valueMap.put("USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE", USERS_UPDATED_STATUS_REGISTRATIONCOMPLETE);
        valueMap.put("USERS.UPDATED.STATUS.REGISTRATIONINPROGRESS", USERS_UPDATED_STATUS_REGISTRATIONINPROGRESS);
        valueMap.put("ELECTRONICWALLETS.CREATED", ELECTRONICWALLETS_CREATED);
        valueMap.put("ELECTRONICWALLETS.UPDATED.DETAILS.MODIFIED", ELECTRONICWALLETS_UPDATED_DETAILS_MODIFIED);
        valueMap.put("ELECTRONICWALLETS.UPDATED.STATUS.APPROVED", ELECTRONICWALLETS_UPDATED_STATUS_APPROVED);
        valueMap.put("ELECTRONICWALLETS.UPDATED.STATUS.COMPLIANCEHOLD", ELECTRONICWALLETS_UPDATED_STATUS_COMPLIANCEHOLD);
        valueMap.put("ELECTRONICWALLETS.UPDATED.STATUS.DELETED", ELECTRONICWALLETS_UPDATED_STATUS_DELETED);
        valueMap.put("UNKNOWN", UNKNOWN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static WebhookNamespaces constructFromString(String toConvert) throws IOException {
        WebhookNamespaces enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static WebhookNamespaces fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of WebhookNamespaces values to list of string values.
     * @param toConvert The list of WebhookNamespaces values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<WebhookNamespaces> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (WebhookNamespaces enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 